version: '3.8'

services:
  # Django Web Service
  web:
    build: .
    container_name: django_web_app
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    environment:
      DEBUG: ${DEBUG:-True}
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-here}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost,127.0.0.1,web}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - django_network

networks:
  django_network:
    driver: bridge
