services:
  # Django Web Service
  web:
    build: .
    container_name: django_web_app
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DEBUG: ${DEBUG:-True}
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-here}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost,127.0.0.1,web}
      DB_HOST: ${DB_HOST:-host.docker.internal}
      DB_PORT: ${DB_PORT:-3306}
      DB_USER: ${DB_USER:-admin}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-sharing}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - django_network

networks:
  django_network:
    driver: bridge
